### ISSUE TITLE
Reg: Info list for Electronics

### ISSUE THREAD

**Issue by NNNILabs** [ThatRedKite/thatkitebot#88]
Here's a better-ordered list for "electronics help" channels:
If you want to start learning:
- Afrotechmods
- GreatScott!
- ElectrBOOM
- Element14 Workbench Wednesdays
- W2AEW
Good source of entertainment and education:
- EEVBlog
- DiodeGoneWild
- Marco Reps
DIY projects with good explanations:
- Electronoobs
- Bitluni
- Leo's Bag of Tricks
Slightly more in-depth:
- Sam-Ben Yaakov

**Comment by Caraffa-git** [comment]
I agree with moving Afrotechmods, Element14 Workbench Wednesdays and W2AEW to "If you want to start learning", maybe ElectrBOOM 101 playlist too. I wouldn't remove anything from this category because the best way to learn is highly subjective and everyone may prefer something different.

Regarding the rest i don't even care because honestly *almost* all of the channels could be lumped under "fun and education"

**Comment by ThatRedKite** [comment]
since caraffa seems busy, this will be added later than 4.0
